apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-deployment
  namespace: lschneck 
  labels:
    app: db
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  minReadySeconds: 20
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
      - envFrom:
        - secretRef:
            name: db-secret
        name: db-deployment
        image:  harbor.dev.afsmtddso.com/lschneck-harbor-project/db@sha256:f9b11e1b4b152118e00857107f5d332e745394afc028c6975ceedf3539749320
        ports:
        - containerPort: 5432
